apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  PORT: "3000"
  REDIS_URL: "redis://redis:6379"      # 'redis' will be a Service in Lab 06
  DB_HOST: "db"
  DB_NAME: {{.Values.config.dbName}}